defaults:
  - default
  - _self_

selector_model:
  sbert_name: "sentence-transformers/all-MiniLM-L6-v2"
  attention_augment: False
  fourier:
    use: False
    mode: "lowpass"
    keep_ratio: 0.5
  loss:
    l_comp: 0.1
    l_s: 0.01
    l_tv: 10.0
    tau: 0.07
    use_null_target: False
  optim:
    lr: 5e-5
    weight_decay: 1e-2
    betas: [0.9, 0.999]

composite:
  selector_threshold: 0.5
  num_stages: 5
  stagewise: true
  stage_epochs: [5, 5, 5, 5, 5]
  loss_weights:
    selector: 1.0
    expert: 1.0

train:
  epochs: 10
  grad_clip: 1.0

data:
  train:
    config: null
  eval:
    config: null

eval:
  eval_only: False
  metrics_only: True
  factor_threshold: null
